### ISSUE TITLE
Out-Of-Order packets cause subtract with overflow

### ISSUE THREAD

**Issue by ValorZard** [gschup/ggrs#11]
I was doing 100 for lag and 10ms for packet drop, and the clients crashe after a few second due to prediciton overlaod

**Comment by gschup** [comment]
Thanks for testing with clumsy! 

Would you be able to provide more information/the exact error that occurred? I don't know what you refer to with "Prediction overload".

**Comment by ValorZard** [comment]
What happens is that when i crank the lag up to 100ms, the game noticably slows down by a lot, and eventually the error "Skipping a frame: PredictionThreshold" is triggered multiple times and the game crashes

**Comment by gschup** [comment]
Inn the examples, the message "skipping a frame: Prediction threshold" is string that gets printed when `advance_frame(...)` returns a 'PredictionThreshold' Error. This normally cannot be the cause of program termination. 

Could you please check again and see what the actual panic was? You can also enable the system variable `RUST_BACKTRACE=1` to get more detailed panic traces

**Comment by ValorZard** [comment]
thread 'main' panicked at 'attempt to subtract with overflow', src\network\udp_protocol.rs:471:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\box_game_spectator.exe 7002 '127.0.0.1:7000'` (exit code: 101)

additionally, the two clients ended up desyncing because they were both lagging like crazy.

**Comment by gschup** [comment]
Thank you!

I will take a look in the coming days!
