### ISSUE TITLE
Remove MAX_PLAYERS

### ISSUE THREAD

**Issue by shelbyd** [gschup/ggrs#26]
**Is your feature request related to a problem? Please describe.**
I'm using ggrs for a 8/9 player PvE game (8 humans, 1 server). I currently, could not construct a P2PSession with more than 4 players due to the `MAX_PLAYERS` limit.

**Describe the solution you'd like**
There should be no imposed limit on the number of players in a game. The documentation can warn about considerations and potential problem at high player counts and optionally log a warning. But ultimately, it should be up to the user of the crate to decide how many players to use ggrs with.

**Additional context**
It may also be fruitful to consider a hub and spoke networking topology to not have network communication scale quadratically in the number of players, letting much larger player counts be feasible.

**Comment by gschup** [comment]
Which version not GGRS do you use? The main branch already does not have `MAX_PLAYERS` anymore. But it has not been published to crates.io yet.

**Comment by shelbyd** [comment]
I'm using main. I haven't actually tried it yet, just assuming based on reading the wrong documentation. My mistake. :sweat_smile:
