### ISSUE TITLE
[Question] Is the SyncTest Mode Suitable for General Purpose Local Play?

### ISSUE THREAD

**Issue by zicklag** [gschup/ggrs#39]
I was just wondering whether the sync test mode makes sense in the context of local play, and whether setting the check distance to 0 or something similar can be done to avoid any extra overhead of rolling back.

**Edit:** Sorry I opened an issue, I just realized you had discussions enabled. This should be converted to a discussion.

**Comment by gschup** [comment]
Yes, in SyncTestSession, all expensive operations are skipped if the check distance is 0 ([like here])(https://github.com/gschup/ggrs/blob/0d70f4524b02a945999cdfed83a111e8c1140ed0/src/sessions/sync_test_session.rs#L121)

**Comment by zicklag** [comment]
Perfect, thanks!
